-- APP在线签约认购：订单表 + 合同签署表（幂等）

CREATE TABLE IF NOT EXISTS `sys_invest_order` (
  `order_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `order_no` varchar(64) NOT NULL COMMENT '订单号',
  `client_req_no` varchar(64) NOT NULL DEFAULT '' COMMENT '客户端请求流水（幂等）',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `user_name` varchar(64) DEFAULT '' COMMENT '用户账号',
  `product_id` bigint(20) NOT NULL COMMENT '产品ID',
  `product_name` varchar(128) NOT NULL COMMENT '产品名称',
  `currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '投资币种',
  `group_mode` char(1) NOT NULL DEFAULT '0' COMMENT '是否拼团（0否1是）',
  `invest_amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '投资金额',
  `single_rate` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT '单购利率(%)',
  `group_rate` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT '拼团利率(%)',
  `effective_rate` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT '实际生效利率(%)',
  `cycle_days` int(11) NOT NULL DEFAULT 1 COMMENT '投资周期(天)',
  `expected_income` decimal(18,6) NOT NULL DEFAULT 0.000000 COMMENT '预计收益',
  `contract_no` varchar(64) NOT NULL COMMENT '合同编号',
  `status` char(1) NOT NULL DEFAULT '0' COMMENT '状态（0持有中 1已完成 2已取消）',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`order_id`),
  UNIQUE KEY `uk_sys_invest_order_no` (`order_no`),
  UNIQUE KEY `uk_sys_invest_order_user_req` (`user_id`,`client_req_no`),
  KEY `idx_sys_invest_order_uid` (`user_id`),
  KEY `idx_sys_invest_order_pid` (`product_id`),
  KEY `idx_sys_invest_order_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='投资订单';

CREATE TABLE IF NOT EXISTS `sys_invest_contract_sign` (
  `sign_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '签署ID',
  `contract_no` varchar(64) NOT NULL COMMENT '合同编号',
  `order_no` varchar(64) NOT NULL COMMENT '订单号',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `product_id` bigint(20) NOT NULL COMMENT '产品ID',
  `contract_text` mediumtext COMMENT '合同快照文本',
  `signature_data` longtext COMMENT '手写签名base64',
  `agreed` char(1) NOT NULL DEFAULT '1' COMMENT '是否同意（0否1是）',
  `sign_time` datetime DEFAULT NULL COMMENT '签约时间',
  `status` char(1) NOT NULL DEFAULT '1' COMMENT '状态（0无效1有效）',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`sign_id`),
  UNIQUE KEY `uk_sys_invest_contract_no` (`contract_no`),
  KEY `idx_sys_invest_contract_order_no` (`order_no`),
  KEY `idx_sys_invest_contract_uid` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='投资合同签署记录';
